# Generated by Django 4.2.6 on 2023-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_itemstatus_service_delete_dailystatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
